version: '3.8'

services:
  # PHP Service
  app:
    build:
      context: .
      dockerfile: build/Dockerfile_laravel_app
    image: php-laravel-app:dev
    container_name: app
    restart: unless-stopped
    volumes:
      - ./app:/var/www
      - ./config/laravel/.env:/var/www/.env
      - ./config/php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./logs/laravel:/var/www/storage/logs
      - web-root:/var/www
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "php", "-v"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    depends_on:
      - app
    restart: unless-stopped
    tty: true
    ports:
      - 6080:80
    volumes:
      - ./app:/var/www
      - ./config/nginx/conf.d/:/etc/nginx/conf.d/
      - ./logs/nginx:/var/log/nginx
      - web-root:/var/www
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - dhparam:/etc/ssl/certs
    networks:
      - app-network

  # MySQL Service
  db:
    image: mariadb
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      SERVICE_NAME: mysql
      SERVICE_TAGS: dev
    volumes:
      - dbdata:/var/lib/mysql/
      - ./config/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network

  # Adminer Service
  adminer:
    container_name: adminer
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080
    networks:
      - app-network

  # Composer Service
  composer:
    container_name: composer
    image: composer
    depends_on: 
      - app
    volumes:
      - ./app:/app
    working_dir: /app
    command: composer install
  
  # Nodejs Service
  node:
    container_name: node
    image: node
    depends_on: 
      - app
    volumes:
      - ./app:/app
    working_dir: /app
    command: npm install

  #Certbot Service
  certbot:
    image: certbot/certbot
    container_name: certbot
    depends_on:
      - webserver
    volumes:
      - web-root:/var/www
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - ./logs/certbot:/var/log/letsencrypt
    #command: certonly --webroot --webroot-path=/var/www --email www@ishipilov.ru --agree-tos --no-eff-email --staging -d ishipilov.ru -d www.ishipilov.ru
    command: certonly --webroot --webroot-path=/var/www --email www@ishipilov.ru --agree-tos --no-eff-email --force-renewal -d ishipilov.ru -d www.ishipilov.ru

volumes:
  dbdata:
  vendor-data:
  node-data:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: ./app
      o: bind
  certbot-etc:
  certbot-var:
  dhparam:
    driver: local
    driver_opts:
      type: none
      device: ./certs/dhparam
      o: bind

networks:
  app-network:
    driver: bridge
    name: laravel-network